# action.yaml
name: 'Update PR Reminder Action'
description: 'A github action to automatically remind PR authors to update their branch when there is a new commit in the base branch'
author: "Bhupesh Varshney"

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'bell'  
  color: 'orange'