on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Update PR Reminder Test
    steps:
      - name: Get Pokemon name
        uses: Bhupesh-V/update-pr-reminder-demo@main